### ISSUE TITLE
oflops installation problem

### ISSUE THREAD

**Issue by gojkog21** [mininet/oflops#3]
Hi,

I've followed steps given there: https://floodlight.atlassian.net/wiki/pages/viewpage.action?pageId=1343657 but I can't install cbench on my ubuntu 16.04.

There is the result of command sudo make install from oflops directory:
**Making install in .
make[1]: Entering directory '/home/gojko/oflops'
/bin/bash ./libtool  --tag=CC   --mode=link gcc  -g -O2 -Wall -I/home/gojko/oflops/openflow/include -Wshadow `pkg-config --cflags libconfig` -static -Wl,-E -L/home/gojko/oflops/openflow/lib `pkg-config --libs libconfig` -o oflops channel_info.o context.o control.o module_run.o module_default.o oflops.o oflops_pcap.o timer_event.o msg.o log.o traffic_generator.o usage.o -ldl -lpcap -lnetsnmp -loflops_test -lpthread 
libtool: link: gcc -g -O2 -Wall -I/home/gojko/oflops/openflow/include -Wshadow -I/usr/local/include -Wl,-E -o oflops channel_info.o context.o control.o module_run.o module_default.o oflops.o oflops_pcap.o timer_event.o msg.o log.o traffic_generator.o usage.o  -L/home/gojko/oflops/openflow/lib -L/usr/local/lib -ldl -lpcap /home/gojko/oflops/.libs/liboflops_test.a /usr/local/lib/libconfig.so -lnetsnmp -lpthread
traffic_generator.o: In function `get_next_pkt':
/home/gojko/oflops/traffic_generator.c:140: undefined reference to `time_diff'
collect2: error: ld returned 1 exit status
Makefile:576: recipe for target 'oflops' failed
make[1]: *** [oflops] Error 1
make[1]: Leaving directory '/home/gojko/oflops'
Makefile:641: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1**

Any ideas?

Thanks,

Gojko

**Comment by intidharbedhief** [comment]
hi,
I have the same error, plz how can i solve it ?? 
Thanks Sir,
Intidhar

**Comment by Ubermenschen7** [comment]
> hi,
> I have the same error, plz how can i solve it ??
> Thanks Sir,
> Intidhar

Hi, i guess this link will help u to solve problem with installation https://github.com/intracom-telecom-sdn/mtcbench/issues/10
